### PR TITLE
Finished functions in model.py, minor cleanup of code

### PR DESCRIPTION
**Pull request by whagestad**

### CODE REVIEW

**Review by xm6264jz — APPROVED** [review]

**Review by xm6264jz — CHANGES_REQUESTED** [review]
@whagestad  in line 17 of database file. Raise an exception error, so that the test can raise an assert error. Thanks

**Comment by whagestad** [comment]
@xm6264jz I am already throwing an exception at line 15, can you tell me more about what you're looking for me to add?

**Comment by xm6264jz** [comment]
@whagestad Raise an error. create an class to raise error. Then use the raised error instead of logging. I am trying to test for duplicate data but it doesn't seem to work without a raised error

**Comment by whagestad** [comment]
Merged branch so Ahmed can continue with database testing.

**Pull request merged**
